---
team_number: 1 # team number to make focus of statistics
replay_length: 2.0  # mins, total time to replay event
event_length: 12.0  # hours, total time of rogaining event
event_name: "X hr Rogaining Event"  # name of rogaining event to be display as title
map_file: "path/to/file"  # path to pdf of map, relative to main.py
control_coordinates: "path/to/file" # path to csv of pixel coordinates of map controls, relative to main.py
map_scale_pixels: "1:100" # scale of how many pixels to metres e.g. 1 pixel = 100 metres